[TG-59 ] JoinGame and ListGameSessionsRepository implemented
the-coolest-developers/TileGame-Core pull request #49
Opened 2021-07-05 15:01 UTC by NickNovic

2021-07-06 18:25 UTC, ArtiomCiobanu commented on Source/TileGameServer/TileGameServer.DataAccess/Entities/GameSession.cs
> +        public List<Guid> PlayersId { get; set; } = new List<Guid>();
PlayerIds

2021-07-06 18:33 UTC, ArtiomCiobanu commented on Source/TileGameServer/TileGameServer.DataAccess/Repositories/ListGameSessionsRepository.cs
> +        public Task SaveChangesAsync()
Вынести в новый интерфейс

2021-07-06 18:37 UTC, ArtiomCiobanu commented on Source/TileGameServer/TileGameServer/Commands/Menu/JoinGameSession.cs
> +                if(!await ListGameSessionsRepository.ExistsWithPlayerAsync(request.UserId))
If(exists)
{
return
}

2021-07-06 18:46 UTC, ArtiomCiobanu commented on Source/TileGameServer/TileGameServer/Controllers/MenuController.cs
> +        public async Task<ActionResult<Unit>> JoinGame([FromBody] Guid SessionId)
Заменить на DTO

2021-07-06 18:46 UTC, ArtiomCiobanu commented on Source/TileGameServer/TileGameServer/Controllers/MenuController.cs
> +                UserId = Guid.Empty,
Использовать User.GetClaim(AppClaimTypes.UserId);

2021-07-06 18:47 UTC, ArtiomCiobanu commented on Source/TileGameServer/TileGameServer.DataAccess/Repositories/ListGameSessionsRepository.cs
> +    public class ListGameSessionsRepository : IListGameSessionsRepository
Переименовать в GameSessionRepository

2021-07-06 18:47 UTC, ArtiomCiobanu commented on Source/TileGameServer/TileGameServer.DataAccess/Repositories/IListGameSessionsRepository.cs
> +    public interface IListGameSessionsRepository : IRepository<GameSession>
Перенести метод в IGameSessionRepository

2021-07-06 18:48 UTC, ArtiomCiobanu commented on Source/TileGameServer/TileGameServer.DataAccess/Repositories/IListGameSessionsRepository.cs
> +    public interface IListGameSessionsRepository : IRepository<GameSession>
И удалить этот интерфейс

2021-07-07 20:15 UTC, Cute-Monster requested changes
1. Make a new branch from current according to the new structure.
2. Fix the mentioned issues

2021-07-08 16:22 UTC, Cute-Monster commented
@NickNovic, I'm closing this PR, cause ths actions shoul be performed

>
>     1. Make a new branch from current according to the new structure.
> 
>     2. Fix the mentioned issues

2021-07-08 16:22 UTC, closed without merging