[TGS-9] GameSessionRepository.cs reworked
the-coolest-developers/TileGame-Core pull request #54
Opened 2021-07-15 11:29 UTC by Cute-Monster

💥

2021-07-15 19:35 UTC, ArtiomCiobanu requested changes

2021-07-15 19:35 UTC, ArtiomCiobanu commented on Source/TileGameServer/TileGameServer.Infrastructure/Models/Player.cs
> +    public class Player
Нужно перенести в DataAccess.Entities

2021-07-15 19:35 UTC, ArtiomCiobanu commented on Source/TileGameServer/TileGameServer/Commands/Menu/CreateGameSession.cs
> +        public class CreateGameSessionResponse : IResponse<Guid>
Может лучше вернуть new Response<T> ?
И чтобы T было моделью с guid полем session id

2021-07-15 19:35 UTC, ArtiomCiobanu commented on Source/TileGameServer/TileGameServer/Commands/Menu/JoinGameSession.cs
> +            public string Result { get; set; }
Как и в предыдущем

2021-07-15 19:35 UTC, ArtiomCiobanu commented on Source/TileGameServer/TileGameServer/Commands/Menu/LeaveGameSession.cs
> +
Здесь наверное тоже

2021-07-15 19:35 UTC, ArtiomCiobanu commented on Source/TileGameServer/TileGameServer/Controllers/MenuController.cs
> +        public async Task<ActionResult<Guid>> CreateGame()
Лучше возвращать модель с полем, у которого будет название

2021-07-15 19:35 UTC, ArtiomCiobanu commented on Source/TileGameServer/TileGameServer/Controllers/MenuController.cs
> +        public async Task<ActionResult<string>> JoinGame([FromBody] JoinGameSessionRequest request)
Тоже лучше вернуть модель

2021-07-16 12:27 UTC, Cute-Monster commented
@NickNovic Fix changes ^^^

2021-07-17 11:36 UTC, ArtiomCiobanu commented on Source/TileGameServer/TileGameServer.DataAccess/Repositories/IEntityFrameworkGameSessionRepository.cs
> +    public interface IEntityFrameworkGameSessionRepository : IRepository<GameSession>
Нужно удалить интерфейс, создал замену в WebApiBaseLibrary

2021-07-18 15:47 UTC, ArtiomCiobanu requested changes

2021-07-18 15:47 UTC, ArtiomCiobanu commented on Source/TileGameServer/TileGameServer/Commands/Menu/CreateGameSession.cs
> +                IJwtGenerator jwtGenerator)
Почему jwtGenerator передаётся в конструктор, но дальше не используется?

2021-07-18 15:47 UTC, ArtiomCiobanu commented on Source/TileGameServer/TileGameServer.DataAccess/Entities/Player.cs
> +namespace TileGameServer.Infrastructure.Models
namespace Должен соответствовать папке
В Rider можно подправить namespace-ы всего солюшна

2021-07-18 15:47 UTC, ArtiomCiobanu commented on Source/TileGameServer/TileGameServer/Commands/Menu/JoinGameSession.cs
> +        }
Добавь сюда новую строку пожалуйста

2021-07-18 15:47 UTC, ArtiomCiobanu commented on Source/TileGameServer/TileGameServer/Commands/Menu/LeaveGameSession.cs
> +                IJwtGenerator jwtGenerator
jwtGenerator тоже почему-то не используется

2021-07-18 15:47 UTC, ArtiomCiobanu commented on Source/TileGameServer/TileGameServer/Commands/Menu/LeaveGameSession.cs
> +        }
Опять нужна новая строка

2021-07-18 15:47 UTC, ArtiomCiobanu commented on Source/TileGameServer/TileGameServer/Controllers/MenuController.cs
> +        public async Task<ActionResult<JoinGameSession.JoinGameSessionResponse>> JoinGame([FromBody] JoinGameSession.JoinGameSessionRequest request)
Перенеси пожалуйста параметр на новую строку (начиная с атрибута FromBody)

2021-07-18 15:47 UTC, ArtiomCiobanu commented on Source/TileGameServer/TileGameServer/Controllers/MenuController.cs
> +        public async Task<ActionResult<LeaveGameSession.LeaveGameSessionResponse>> Leave([FromBody] LeaveGameSession.LeaveGameSessionRequest request)
Здесь лучше тоже перенести на новую строку

2021-07-18 15:47 UTC, ArtiomCiobanu commented on Source/TileGameServer/TileGameServer/Controllers/MenuController.cs
> +            var userId = Guid.Parse(User.GetClaim(ApplicationClaimTypes.UserId).Value);
Может userId лучше сделать свойство в контроллере, чтобы не парсить отдельно в каждом методе? 
Или можно поставить в базовый класс

2021-07-21 16:19 UTC, ArtiomCiobanu approved these changes

2021-07-22 09:51 UTC, merged