[TGS-56] Created TileGameServer.BaseLibrary project
the-coolest-developers/TileGame-Core pull request #57
Opened 2021-07-28 19:00 UTC by ArtiomCiobanu

2021-07-28 19:04 UTC, NickNovic approved these changes

2021-07-28 19:07 UTC, Cute-Monster requested changes

2021-07-28 19:07 UTC, Cute-Monster commented on Source/TileGameServer/TileGameServer.Domain/TileGameServer.Domain.csproj
> +        <TargetFramework>net5.0</TargetFramework>
Add versionprefix and postfix

2021-07-28 20:54 UTC, ArtiomCiobanu commented on Source/TileGameServer/TileGameServer.Domain/TileGameServer.Domain.csproj
> +        <TargetFramework>net5.0</TargetFramework>
Done

2021-07-29 10:04 UTC, Cute-Monster requested changes

2021-07-29 10:04 UTC, Cute-Monster commented on Source/TileGameServer.BaseLibrary/TileGameServer.BaseLibrary/TileGameServer.BaseLibrary.csproj
> +        <TargetFramework>net5.0</TargetFramework>
the same as was before

2021-07-29 10:04 UTC, Cute-Monster commented on Source/TileGameServer.BaseLibrary/TileGameServer.BaseLibrary.Domain/TileGameServer.BaseLibrary.Domain.csproj
> +        <TargetFramework>net5.0</TargetFramework>
and here

2021-07-29 13:03 UTC, ArtiomCiobanu commented on Source/TileGameServer.BaseLibrary/TileGameServer.BaseLibrary.Domain/TileGameServer.BaseLibrary.Domain.csproj
> +        <TargetFramework>net5.0</TargetFramework>
Done

2021-07-29 13:03 UTC, ArtiomCiobanu commented on Source/TileGameServer.BaseLibrary/TileGameServer.BaseLibrary/TileGameServer.BaseLibrary.csproj
> +        <TargetFramework>net5.0</TargetFramework>
Done

2021-07-29 15:00 UTC, Cute-Monster approved these changes

2021-07-29 16:12 UTC, merged