[TGS-55] Created InSession solution and added diagrams
the-coolest-developers/TileGame-Core pull request #58
Opened 2021-07-29 20:21 UTC by ArtiomCiobanu

2021-07-29 20:28 UTC, Cute-Monster requested changes

2021-07-29 20:28 UTC, Cute-Monster commented on Source/TileGameServer.InSession/TileGameServer.InSession/TileGameServer.InSession.csproj
> +        <TargetFramework>net5.0</TargetFramework>
Add version suffix and prefix
+ Add BuildOutput setting(copy from other csproj)

2021-07-29 20:35 UTC, ArtiomCiobanu commented on Source/TileGameServer.InSession/TileGameServer.InSession/TileGameServer.InSession.csproj
> +        <TargetFramework>net5.0</TargetFramework>
Done

2021-07-30 14:58 UTC, Cute-Monster submitted a review, later dismissed

2021-07-30 18:25 UTC, merged